version: "3.8"

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB default port
    volumes:
      - mongo-data:/data/db  # Use Docker volume for persistent storage
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Optional: Username for MongoDB
      MONGO_INITDB_ROOT_PASSWORD: example  # Optional: Password for MongoDB
    networks:
      - backend

  # Other services (admin-service, student-service, etc.)
  admin-service:
    build: ./services/admin-service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - backend

  student-service:
    build: ./services/student-service
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    networks:
      - backend

  teacher-service:
    build: ./services/teacher-service
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
    networks:
      - backend

  # Optional: Reverse Proxy (Nginx)
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - admin-service
      - student-service
      - teacher-service
    networks:
      - backend

networks:
  backend:
    driver: bridge

# Define the volume that MongoDB will use
volumes:
  mongo-data:
    driver: local
