version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db # MongoDB data volume
      - ./data/initdb.d/init.js:/docker-entrypoint-initdb.d/init.js # Mount init.js for initialization
    ports:
      - "27017:27017"
    networks:
      - backend
    restart: always

  # Admin Service
  admin-service:
    build: ./services/admin-service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - backend

  # Student Service
  student-service:
    build: ./services/student-service
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    networks:
      - backend

  # Teacher Service
  teacher-service:
    build: ./services/teacher-service
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
    networks:
      - backend

  # Evaluation Service
  re-evaluation-service:
    build: ./services/re-evaluation-service
    ports:
      - "8003:8003"
    depends_on:
      - mongodb
    networks:
      - backend

  # Auth Service (Optional)
  # Reverse Proxy: Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Mount the Nginx configuration file
    depends_on:
      - admin-service
      - student-service
      - teacher-service
      - re-evaluation-service
    networks:
      - backend

networks:
  backend:
    driver: bridge

# Define the volume that MongoDB will use
volumes:
  mongo-data:
    driver: local
